{% set name = "nanoSCULPT" %}
{% set version = "1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://bitbucket.org/arunpksh/nanosculpt/get/992a41dd78d9949e6f6ab2ad67ff1bd39e013a0e.tar.gz
  sha256: 99b0fba7e960d9a76a157f0f96cb487d44f6f4bb7a8526534c201b19cc6e0eca
  patches:
    - make.patch

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
  run:

test:
  commands:
    - nanoSCULPT Example.nsparam
  files:
    - Example.nsparam
    - Teddy.pos
    - teddy_scaled.obj

about:
  home: https://bitbucket.org/arunpksh/nanosculpt
  summary: 'nanoSCULPT is a tool to generate realistic configurations for Atomistic simulations'
  description: |
    nanoSCULPT was originally hosted at the individual development 
    groups of the tool, viz. FAU Erlangen-Nürnberg and Uni Stuttgart. 
    This repository now brings the efforts of the two groups into one 
    place.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://bitbucket.org/arunpksh/nanosculpt
  dev_url: https://bitbucket.org/arunpksh/nanosculpt

extra:
  recipe-maintainers:
    - jan-janssen
